DEVICE_PATH := device/motorola/bogota

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic

BOARD_KERNEL_PAGESIZE := 4096
BOARD_BOOT_HEADER_VERSION := 4
BOARD_HAS_NO_RECOVERY := true
BOARD_USES_VENDOR_BOOTIMAGE := true

BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_FLASH_BLOCK_SIZE := 262144

TW_THEME := portrait_hdpi
TW_DEVICE_VERSION := Angel_Build_v1
