name: Build TWRP Moto G56

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Recovery
      uses: shotgun-p/recovery-builder@main
      with:
        MANIFEST_URL: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
        MANIFEST_BRANCH: 'twrp-12.1'
        DEVICE_PATH: 'bogota'
        DEVICE_NAME: 'bogota'
        BUILD_TARGET: 'vendorboot'
        
